services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./docs:/app/docs
      - ./db:/app/db
    environment:
      - PORT=3030
      - MARKDOWN_DIR=/app/docs
      - DB_FILE=/app/db/data.json
    restart: unless-stopped
